from django.conf.urls.defaults import *
from django.views.generic import TemplateView

urlpatterns = patterns('politics.views',
    url(r'^$','home'),
    url(r'^volunteer/$', TemplateView.as_view(template_name="politics/volunteer.html")),
    url(r'^savevolunteer/$','volunteer'),
    url(r'^about/$', TemplateView.as_view(template_name="politics/about.html")),
    url(r'^login/$','login'),
    url(r'^forestheights/$','login'),
    url(r'^mygov/$',TemplateView.as_view(template_name="politics/about.html")),
    url(r'^demo/openletter/$',TemplateView.as_view(template_name="politics/openletterdemo.html")),
    url(r'^demo/politician/$',TemplateView.as_view(template_name="politics/politiciandemo.html")),
    url(r'^privacypolicy/$',TemplateView.as_view(template_name="politics/privacy.html")),
    url(r'^logout/$','logout_view'),
    url(r'^engage/$','submit_1'),
    url(r'^politicians/$','politicians'),
    url(r'^create-draft/$','create_draft'),
    url(r'^create-draft1/$','create_draft1'),
    url(r'^save1/$','save_1'),
    url(r'^save2/$','save_2'),
    url(r'^save3/$','save_3'),
    url(r'^register/$','register'),
    url(r'^register/extrarep/(?P<unique>[^/]+)/$','register_extra_rep'),
    url(r'^register_location/$','register_location'),
    url(r'^profile/$','my_politics'),
    url(r'^email/page/$','email_page'),
    url(r'^load/my_politics_pagination/$','my_politics_pagination'),
    url(r'^load/issues_letters/$','issues_pagination'),
    #url(r'^load/issues/$','load_issues'),
    url(r'^load/letters/$','load_letters'),
    url(r'^addparty/$','add_party'),
    url(r'^load/politician/letter_box/$','load_politician_letters'),
    url(r'^follow_politician/$','follow_politician'),
    url(r'^follow_open_letter/$','follow_open_letter'),
    url(r'^load/congress/$','congress_letters'),
    url(r'^load/letterbox/politician/$','letterbox_politician'),
    url(r'^load/letterbox/issue/$','letterbox_issue'),
    url(r'^load/polilist/$','polilist'),
    url(r'^load/letter_box/$','letter_box'),
    url(r'^load/lettersort/$','open_letter_sort'),
    url(r'^load/my_politics_letters/$','my_politics_letters'),
    url(r'^update_profile/$','update_profile'),
    url(r'^update_location/$','update_location'),
    url(r'^email/$','email'),
    url(r'^load/mypoliticians/$','my_view'),
    url(r'^load/politicians/(?P<state>[^/]+)/$','add_politicians'),
    url(r'^load/(?P<state>[^/]+)/$','state'),
    url(r'^load/comments/(?P<target>[^/]+)/(?P<slug>[^/]+)/$','load_comments'),
    url(r'searching/$','search'),
    url(r'^searchletters/(?P<query>[^/]+)/$','letter_search'),
    url(r'^search/(?P<query>[^/]+)/$','poli_search'),
    url(r'^create/$','create'),
    url(r'^mylocation/$','localize'),
    url(r'^next/$','view_pages'),
    url(r'^legislators/$','legislators'),
    #url(r'^congressional-committees/$','congress_committee'),
    url(r'^location/$','location_save'),
    url(r'^hlocation/$','hlocation_save'),
    url(r'^mypoliticians/(?P<state>[^/]+)/(?P<city>[^/]+)/(?P<latitude>[^/]+)/(?P<longitude>[^/]+)/$','my_politicians'),
    url(r'^save/$', 'save_page'),
    url(r'^issues/$', 'issues'),
    url(r'^issue/(?P<issue>[^/]+)/(?P<letter_type>[^/]+)/$', 'byissue'),
    url(r'^issue/$', 'issue_save'),
    url(r'^about/$', 'about'),
    url(r'^upvote/$', 'up'),
    url(r'^up/$', 'page_up'),
    url(r'^replyupvote/$', 'replyup'),
    url(r'^replydownvote/$', 'replydown'),
    url(r'^downvote/$', 'down'),
    url(r'^down/$', 'page_down'),
    url(r'^mention/(?P<slug>[^/]+)/$', 'upvote_all'),
    url(r'^mentionone/(?P<slug>[^/]+)/$', 'upvote_one'),
    url(r'^issuesearch/$', 'search_issues'),
    url(r'^unreportreply/$', 'unreport_reply'),
    url(r'^profile/$', 'politipage'),
    #url(r'^politician/(?P<first>[^/]+)/(?P<last>[^/]+)/$', 'politician_profile'),
    #url(r'^(?P<username>[a-zA-Z0-9_-]+)/profile/$', 'politipage'),
    url(r'^openletter/(?P<slug>[^/]+)/$', 'view_ask'),
    url(r'^openletters/(?P<slug>[^/]+)/$', 'open_letter'),
    url(r'^requestpolitician/(?P<slug>[^/]+)/$', 'request_politician'),
    url(r'^responsepolitician/(?P<slug>[^/]+)/$', 'request_response'),
    url(r'^politician_search/(?P<slug>[^/]+)/$', 'politician_search'),
    url(r'^comment/up/$', 'comment_up'),
    url(r'^comment/down/$', 'comment_down'),
    url(r'^reply/up/$','reply_up'),
    url(r'^reply/down/$','reply_down'),
    url(r'^comment/(?P<slug>[^/]+)/$', 'save_comment'),
    url(r'^reply/(?P<slug>[^/]+)/(?P<comment_id>\d+)/$', 'save_reply'),
    url(r'^open_up/$', 'open_letter_up'),
    url(r'^open_down/$', 'open_letter_down'),
    url(r'^politicians/(?P<unique>[^/]+)/$', 'politician_profile'),
    #url(r'^(?P<slug>[^/]+)/mention/(?P<bioguide_id>[^/]+)/$', 'mention'),
    url(r'^(?P<slug>[^/]+)/reply/$', 'reply'),
    url(r'^(?P<slug>[^/]+)/favorite/$', 'favorite'),
    url(r'^report/(?P<id>[0-9]+)/(?P<slug>[^/]+)/$', 'report'),
    url(r'^report_reply/(?P<id>[0-9]+)/(?P<slug>[^/]+)/$','report_reply'),
    url(r'^(?P<slug>[^/]+)/replyreport/$', 'replyreport'),
    url(r'^(?P<slug>[^/]+)/source/$', 'source'),
    url(r'^(?P<slug>[^/]+)/cite/$', 'cite'),
    url(r'^(?P<slug>[^/]+)/upvote/$', 'upvote'),
    url(r'^(?P<slug>[^/]+)/downvote/$', 'downvote'),
    url(r'^(?P<slug>[^/]+)/replyvote/$', 'replyvote'),
    url(r'^(?P<slug>[^/]+)/replydownvote/$', 'replydownvote'),
    url(r'^(?P<slug>[^/]+)/comment/$', 'comment'),
    #url(r'^(?P<slug>[^/]+)/mention/(?P<state>[^/]+)/(?P<title>[^/]+)/(?P<first>[^/]+)/(?P<last>[^/]+)/(?P<p_id>[^/]+)/$', 'state_mention'),
                       )